import AppKit
import Combine
import ImageIO
import UniformTypeIdentifiers

/// Запись истории буфера обмена.
struct ClipItem: Identifiable, Equatable {
    enum Kind: Equatable {
        case text(String)
        case url(URL)
        case image(NSImage)
    }

    let id: UUID
    let date: Date
    let kind: Kind
    /// Отпечаток содержимого: по нему ловим повторы, не сравнивая мегабайты данных.
    let signature: String

    init(id: UUID = UUID(), date: Date = Date(), kind: Kind, signature: String? = nil) {
        self.id = id
        self.date = date
        self.kind = kind
        self.signature = signature ?? kind.defaultSignature
    }

    var isImage: Bool { if case .image = kind { return true }; return false }

    /// Сколько символов текста показываем и по скольким ищем. В строку влезает
    /// пара сотен, а скопировать могут и мегабайтный лог: и разбор такого текста,
    /// и вёрстка его в `Text` вешают главный поток на каждой перерисовке.
    static let previewLimit = 500

    var preview: String {
        switch kind {
        case .text(let s):
            // prefix — до чистки: она сама по себе проходит всю строку.
            return s.prefix(Self.previewLimit)
                .trimmingCharacters(in: .whitespacesAndNewlines)
                .replacingOccurrences(of: "\n", with: " ")
        case .url(let u):
            // Путь и кириллица читаются лучше, чем file:///…%D0%9F… и /wiki/%D0%9A%D0%BE%D1%82.
            // В буфер при этом вернётся исходный, закодированный адрес.
            let raw = u.isFileURL ? u.path : u.absoluteString
            return raw.removingPercentEncoding ?? raw
        case .image: return "Изображение"
        }
    }

    var icon: String {
        switch kind {
        case .text: return "text.alignleft"
        case .url: return "link"
        case .image: return "photo"
        }
    }

    static func == (a: ClipItem, b: ClipItem) -> Bool { a.id == b.id }
}

extension ClipItem.Kind {
    /// Хэш вместо самого значения: история держит до 50 записей, копий текста хватит и без этого.
    var defaultSignature: String {
        switch self {
        case .text(let s): return "t:\(s.utf8.count):\(ClipSignature.hash(s))"
        case .url(let u): return "u:\(u.absoluteString)"
        case .image(let i): return "i:\(UInt(bitPattern: ObjectIdentifier(i).hashValue))"
        }
    }
}

/// Отпечаток текста по байтам.
///
/// `String.hashValue` и `String.count` нормализуют юникод и обходят строку посимвольно:
/// на мегабайтном тексте это сотни миллисекунд заблокированного главного потока
/// (на строке-мосте из NSPasteboard — секунды). Байты дают тот же ответ в разы дешевле.
enum ClipSignature {
    static func hash(_ s: String) -> Int {
        var hasher = Hasher()
        let done: Bool? = s.utf8.withContiguousStorageIfAvailable { buffer in
            hasher.combine(bytes: UnsafeRawBufferPointer(buffer))
            return true
        }
        if done != true {
            // Строка без сплошного хранилища (мост на NSString) — копируем байты.
            Array(s.utf8).withUnsafeBytes { hasher.combine(bytes: $0) }
        }
        return hasher.finalize()
    }
}

/// История буфера обмена (поллинг changeCount).
///
/// Содержимое читается только когда счётчик изменился: чтение на каждом тике
/// греет систему и заставляет менеджеры паролей считать, что за ними следят.
/// Всё живёт в памяти — на диск история буфера не пишется.
@MainActor final class ClipboardService: ObservableObject {
    @Published private(set) var items: [ClipItem] = []

    /// Метки Pasteboard, которыми 1Password и другие помечают приватные вставки.
    /// Проверяются до чтения содержимого.
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private static let pollInterval: TimeInterval = 0.3

    private let pasteboard = NSPasteboard.general
    private let settings = Settings.shared

    private var timer: Timer?
    private var lastChangeCount = 0
    private var bag = Set<AnyCancellable>()

    // MARK: — жизненный цикл

    func start() {
        // То, что лежало в буфере до запуска, не забираем: там может быть чужой пароль.
        lastChangeCount = pasteboard.changeCount

        guard bag.isEmpty else { return }
        settings.$clipboardEnabled
            .sink { [weak self] enabled in
                // @Published отдаёт значение до присвоения, поэтому смотрим на пришедшее.
                if enabled { self?.startTimer() } else { self?.stopTimer() }
            }
            .store(in: &bag)
        settings.$clipboardLimit
            .sink { [weak self] limit in self?.trim(to: limit) }
            .store(in: &bag)
    }

    func stop() {
        stopTimer()
        bag.removeAll()
    }

    private func startTimer() {
        guard timer == nil else { return }
        // Скопированное при выключенном слежении в историю не подтягиваем.
        lastChangeCount = pasteboard.changeCount

        let t = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            // Таймер главного цикла — значит, уже на главном акторе.
            MainActor.assumeIsolated { self?.tick() }
        }
        t.tolerance = 0.1
        // .common — иначе поллинг замирает на время меню и скролла.
        RunLoop.main.add(t, forMode: .common)
        timer = t
        Log.clipboard.info("слежение за буфером включено")
    }

    private func stopTimer() {
        guard timer != nil else { return }
        timer?.invalidate()
        timer = nil
        Log.clipboard.info("слежение за буфером выключено")
    }

    // MARK: — опрос

    private func tick() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard settings.clipboardEnabled else { return }
        capture()
    }

    private func capture() {
        guard !isPrivate() else {
            Log.clipboard.debug("запись помечена как приватная — пропущена")
            return
        }

        if let url = fileURL() {
            push(kind: .url(url))
            return
        }

        if let raw = pasteboardText() {
            let text = raw.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { return }
            if let link = webURL(from: text) {
                push(kind: .url(link))
            } else {
                push(kind: .text(raw))
            }
            return
        }

        if let data = imageData() {
            captureImage(data)
        }
    }

    /// Хоть одна приватная метка на самом Pasteboard или на любом его элементе.
    private func isPrivate() -> Bool {
        if let types = pasteboard.types, types.contains(where: { Self.privateTypes.contains($0.rawValue) }) {
            return true
        }
        guard let items = pasteboard.pasteboardItems else { return false }
        return items.contains { item in
            item.types.contains { Self.privateTypes.contains($0.rawValue) }
        }
    }

    /// Текст буфера обычной swift-строкой.
    ///
    /// `string(forType:)` отдаёт строку-мост на NSString: обрезка мегабайтного текста
    /// такой строки занимает больше полсекунды, а длина — секунду с лишним, и всё это
    /// на главном потоке. Из байтов получается обычная строка, и те же операции —
    /// миллисекунды. `string(forType:)` остаётся запасным путём для нестандартных меток.
    private func pasteboardText() -> String? {
        if let data = pasteboard.data(forType: .string),
           let text = String(data: data, encoding: .utf8) {
            return text
        }
        return pasteboard.string(forType: .string)
    }

    private func fileURL() -> URL? {
        guard let types = pasteboard.types, types.contains(.fileURL) else { return nil }
        return (NSURL(from: pasteboard) as URL?)?.standardizedFileURL
    }

    private func webURL(from text: String) -> URL? {
        // utf8.count — O(1) для обычной строки, в отличие от count с его посимвольным обходом.
        guard text.utf8.count <= 2048, !text.contains(" "),
              let url = URL(string: text),
              let scheme = url.scheme?.lowercased() else { return nil }
        switch scheme {
        case "http", "https": return url.host == nil ? nil : url
        case "file": return url
        default: return nil
        }
    }

    private func imageData() -> Data? {
        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            if let data = pasteboard.data(forType: type), !data.isEmpty { return data }
        }
        return nil
    }

    /// Скриншот может весить десятки мегабайт — уменьшаем и хэшируем вне главного актора.
    private func captureImage(_ data: Data) {
        Task.detached(priority: .utility) { [weak self] in
            guard let thumb = ClipThumbnail.make(from: data) else { return }
            await self?.append(thumbnail: thumb.png, signature: thumb.signature)
        }
    }

    private func append(thumbnail png: Data, signature: String) {
        // Пока считалось превью, слежение могли выключить — тогда записи не место в истории.
        guard settings.clipboardEnabled, let image = NSImage(data: png) else { return }
        push(kind: .image(image), signature: signature)
    }

    // MARK: — история

    private func push(kind: ClipItem.Kind, signature: String? = nil) {
        let sign = signature ?? kind.defaultSignature

        // Повтор того же значения не плодит запись — только освежает дату и поднимает наверх.
        if let index = items.firstIndex(where: { $0.signature == sign }) {
            let old = items[index]
            let refreshed = ClipItem(id: old.id, date: Date(), kind: old.kind, signature: old.signature)
            if index == 0 {
                items[0] = refreshed
            } else {
                items.remove(at: index)
                items.insert(refreshed, at: 0)
            }
            return
        }

        items.insert(ClipItem(kind: kind, signature: sign), at: 0)
        trim(to: settings.clipboardLimit)
    }

    private func trim(to limit: Int) {
        let maxCount = max(5, limit)
        guard items.count > maxCount else { return }
        items.removeLast(items.count - maxCount)
    }

    // MARK: — действия

    /// Положить запись обратно в буфер обмена.
    func copyBack(_ item: ClipItem) {
        switch item.kind {
        case .text(let s):
            pasteboard.clearContents()
            pasteboard.setString(s, forType: .string)
        case .url(let u):
            pasteboard.clearContents()
            // NSURL кладёт только public.url (и file-url с NSFilenamesPboardType) —
            // без текстовой метки Cmd-V в любое текстовое поле вставит пустоту.
            pasteboard.writeObjects([u as NSURL])
            pasteboard.setString(u.isFileURL ? u.path : u.absoluteString, forType: .string)
        case .image(let image):
            // Сначала данные, потом clearContents: иначе на битой картинке
            // мы бы просто стёрли пользователю буфер и ничего не положили взамен.
            guard let tiff = image.tiffRepresentation else { return }
            pasteboard.clearContents()
            pasteboard.setData(tiff, forType: .tiff)
        }
        // Своя же запись не должна вернуться в историю дублем на следующем тике.
        lastChangeCount = pasteboard.changeCount

        if let index = items.firstIndex(where: { $0.id == item.id }) {
            let old = items[index]
            let refreshed = ClipItem(id: old.id, date: Date(), kind: old.kind, signature: old.signature)
            items.remove(at: index)
            items.insert(refreshed, at: 0)
        }
    }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
    }

    func clearAll() {
        items.removeAll()
    }
}

/// Превью картинки: считается в фоне, наружу отдаёт только Sendable-значения.
enum ClipThumbnail {
    /// Максимальная сторона превью, px: держать в памяти исходные скриншоты незачем.
    static let maxPixel: CGFloat = 400

    static func make(from data: Data) -> (png: Data, signature: String)? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxPixel
        ]
        guard let cg = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }

        let out = NSMutableData()
        guard let dest = CGImageDestinationCreateWithData(out, UTType.png.identifier as CFString, 1, nil) else { return nil }
        CGImageDestinationAddImage(dest, cg, nil)
        guard CGImageDestinationFinalize(dest) else { return nil }

        var hasher = Hasher()
        hasher.combine(data)
        return (out as Data, "i:\(data.count):\(hasher.finalize())")
    }
}
